# Generated by Django 5.2 on 2025-05-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='prix',
            field=models.FloatField(default=0.0),
        ),
    ]
