# Generated by Django 5.2 on 2025-05-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_piece_prix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='prix',
            new_name='prix_brut',
        ),
        migrations.AddField(
            model_name='piece',
            name='prix_montant',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='piece',
            name='prix_net',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='piece',
            name='prix_vente',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='piece',
            name='prix_vente_reduction',
            field=models.FloatField(default=0.0),
        ),
    ]
