# Generated by Django 5.2 on 2025-05-07 12:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_prix_piece_prix_brut_piece_prix_montant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='commande',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='avion',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='prix_vente_reduction',
        ),
        migrations.AddField(
            model_name='piece',
            name='reduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='piece',
            name='voiture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='prix_brut',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='piece',
            name='prix_montant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='piece',
            name='prix_net',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='piece',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='piece',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
    ]
